//
//  MoviesConfigurator.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension MoviesInteractor: MoviesViewControllerOutput, MoviesRouterDataSource, MoviesRouterDataDestination {
}

extension MoviesPresenter: MoviesInteractorOutput {
}

class MoviesConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MoviesConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MoviesViewController) {
        
        let presenter = MoviesPresenter()
        presenter.output = viewController
        
        let interactor = MoviesInteractor()
        interactor.output = presenter
        
        let router = MoviesRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
