//
//  MoviesViewController.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MoviesViewControllerInput {
    
}

protocol MoviesViewControllerOutput {
    
}

class MoviesViewController: UIViewController, MoviesViewControllerInput {
    
    var output: MoviesViewControllerOutput?
    var router: MoviesRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        MoviesConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
    
//    private func bindCollectionView() {
//        items
//            .bind(to: collectionView.rx.items(cellIdentifier: "\(MoviesCell.self)", cellType: StocksChartCollectionCell.self)) { ( index, element, cell) in
//                cell.chartDayLabel.text = element
//                cell.setDidSelect(delegate: self, index: index, callback: { (_, index) in
//                    self.subscribe(with: index)
//                })
//            }
//            .disposed(by: disposeBag)
//    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension MoviesViewController: MoviesPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
