//
//  FindRouter.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol FindRouterInput {
    
}

protocol FindRouterDataSource: class {
    
}

protocol FindRouterDataDestination: class {
    
}

class FindRouter: FindRouterInput {
    
    weak var viewController: FindViewController!
    weak private var dataSource: FindRouterDataSource!
    weak var dataDestination: FindRouterDataDestination!
    
    init(viewController: FindViewController, dataSource: FindRouterDataSource, dataDestination: FindRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
