//
//  FindInteractor.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol FindInteractorInput {
    
}

protocol FindInteractorOutput {
    
}

protocol FindDataSource {
    
}

protocol FindDataDestination {
    
}

class FindInteractor: FindInteractorInput, FindDataSource, FindDataDestination {
    
    var output: FindInteractorOutput?
    
    // MARK: Business logic
    

}
