//
//  FindViewController.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol FindViewControllerInput {
    
}

protocol FindViewControllerOutput {
    
}

class FindViewController: UIViewController, FindViewControllerInput {
    
    var output: FindViewControllerOutput?
    var router: FindRouter?
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        FindConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: Requests
    
    
    // MARK: Display logic
    
//    override var preferredStatusBarStyle: UIStatusBarStyle {
//        return .lightContent
//    } 
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension FindViewController: FindPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
