//
//  MovieDetailsConfigurator.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension MovieDetailsInteractor: MovieDetailsViewControllerOutput, MovieDetailsRouterDataSource, MovieDetailsRouterDataDestination {
}

extension MovieDetailsPresenter: MovieDetailsInteractorOutput {
}

class MovieDetailsConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MovieDetailsConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MovieDetailsViewController) {
        
        let presenter = MovieDetailsPresenter()
        presenter.output = viewController
        
        let interactor = MovieDetailsInteractor()
        interactor.output = presenter
        
        let router = MovieDetailsRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
