//
//  MovieDetailsRouter.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol MovieDetailsRouterInput {
    
}

protocol MovieDetailsRouterDataSource: class {
    
}

protocol MovieDetailsRouterDataDestination: class {
    var movieDetails: Result? { get set }
}

class MovieDetailsRouter: MovieDetailsRouterInput {
    
    weak var viewController: MovieDetailsViewController!
    weak private var dataSource: MovieDetailsRouterDataSource!
    weak var dataDestination: MovieDetailsRouterDataDestination!
    
    init(viewController: MovieDetailsViewController, dataSource: MovieDetailsRouterDataSource, dataDestination: MovieDetailsRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
