//
//  MovieDetailsInteractor.swift
//  MyTMDb
//
//  Created by José Victor Pereira Costa on 12/01/19.
//  Copyright (c) 2019 José Victor Pereira Costa. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol MovieDetailsInteractorInput {
    
}

protocol MovieDetailsInteractorOutput {
    
}

protocol MovieDetailsDataSource {
    
}

protocol MovieDetailsDataDestination {
    
}

class MovieDetailsInteractor: MovieDetailsInteractorInput, MovieDetailsDataSource, MovieDetailsDataDestination {
    
    var output: MovieDetailsInteractorOutput?
    
    // MARK: Business logic
    

}
